[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "x-fuse"
version = "0.1.0"
description = "XCT and XRDCT Fusion Toolkit"
requires-python = ">=3.10"
authors = [
    { name = "Calum Green", email = "calum.green17@imperial.ac.uk" },
]
dependencies = [
    "featup",
    "hr_dv2",
    "opencv-python>=4.13.0.92",
    "porespy>=3.0.2",
    "torch>=2.0",
]

[project.optional-dependencies]
cuda = [
    "torch>=2.0",
]
cpu = [
    "torch>=2.0",
]
dev = [
    "pytest>=7.0",
    "pytest-cov>=4.0",
    "pytest-benchmark>=4.0",
    "ipython>=7.0",
    "jupyter>=1.0",
]

[tool.hatch.metadata]
allow-direct-references = true

[tool.uv.sources]
featup = { workspace = true }
hr_dv2 = { workspace = true }

[tool.uv.workspace]
members = [
    "FeatUp",
    "HR-Dv2",
]
